version: "4.25.2"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "asd"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "1111"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
