import css from "@/styles/home.module.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const Home = () => {

  return (
    <main className={css.main}>
     <h1>HOME</h1>
    </main>
  );
};

export default Home;